### ISSUE TITLE
Code Error in TestNoneequilibrium3.m

### ISSUE THREAD

**Issue by tuffwave** [gaofengnan/WAVE#1]
First of all, I'm glad to be able to use your MATLAB code. Unfortunately, when I run TestNonequilibrium3.m, I get an error on line 133 in the code Tracefit=sfit(j).ss(:,lo);. The error message is ss is an unrecognized field. I would like to know how I can fix this part.

**Comment by admixture-CT** [comment]
Thanks for using our code.  This error is most likely caused by selecting a folder with the wrong format when using TestNonequilibrium3.m.  You can see "User guide" section in "README.md" for more detail, and follow the steps in "Test TestNonequilibrium3 with simulated data" section to learn how to use our code (Note that when generating simulated data, the state system selected using parameter "mode" in line 18 of MakeNonequilibriumHMMPoissonData.m needs to correspond to that selected using a similar parameter "mode" in line 31 of the evaluation program NonequilibriumCompare.m). The annotation on lines 21-38 in TestNonequilibrium3.m also specify the format of the selected folder.

We provide a test folder in GitHub named by "test". Trajectories in this folder were generated by MakeNonequilibriumHMMPoissonData.m with "mode=1;" in line 18(non-overlapping 7-state system [A-1]). You can download this folder and delete the BNESTAnanysis.mat and BestHMMParameters2.mat in it, analyze the data with TestNonequilibrium3.m, and then evaluate the analysis results with NonequilibriumCompare.m ("mode=1;" in line 31). You can also enable commented out codes in line 561-649 of NonequilibriumCompare.m, which enable figure plotting for each FRET trajectory.

Technically, in TestNonequilibrium3.m, the structure "sfit(j).ss(:,lo)" used in line 133 is defined by "[sfit,MDLN]=MDLMulti(S);" in line 116, while the structure "S" records all FRET efficiency trajectories in selected folder ("S" is defined by "Load data" part in line 77-104).  Thus, if no specific format files are included in the selected folder, or some files are abnormal, "sfit(j).ss(:,lo)" will become an  unrecognized field.

**Comment by tuffwave** [comment]
> Thanks for using our code. This error is most likely caused by selecting a folder with the wrong format when using TestNonequilibrium3.m. You can see "User guide" section in "README.md" for more detail, and follow the steps in "Test TestNonequilibrium3 with simulated data" section to learn how to use our code (Note that when generating simulated data, the state system selected using parameter "mode" in line 18 of MakeNonequilibriumHMMPoissonData.m needs to correspond to that selected using a similar parameter "mode" in line 31 of the evaluation program NonequilibriumCompare.m). The annotation on lines 21-38 in TestNonequilibrium3.m also specify the format of the selected folder.
> 
> We provide a test folder in GitHub named by "test". Trajectories in this folder were generated by MakeNonequilibriumHMMPoissonData.m with "mode=1;" in line 18(non-overlapping 7-state system [A-1]). You can download this folder and delete the BNESTAnanysis.mat and BestHMMParameters2.mat in it, analyze the data with TestNonequilibrium3.m, and then evaluate the analysis results with NonequilibriumCompare.m ("mode=1;" in line 31). You can also enable commented out codes in line 561-649 of NonequilibriumCompare.m, which enable figure plotting for each FRET trajectory.
> 
> Technically, in TestNonequilibrium3.m, the structure "sfit(j).ss(:,lo)" used in line 133 is defined by "[sfit,MDLN]=MDLMulti(S);" in line 116, while the structure "S" records all FRET efficiency trajectories in selected folder ("S" is defined by "Load data" part in line 77-104). Thus, if no specific format files are included in the selected folder, or some files are abnormal, "sfit(j).ss(:,lo)" will become an unrecognized field.

Thanks a lot! I fixed this issue accoriding to your comments.
